### PR TITLE
Explore haplotype structure via age estimation

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR adds a notebook with an exploratory analysis of haplotype structure using the estimator for haplotype age from Mathieson and McVean. Also updates the submodule with some supporting functions.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @cclarkson, there is a [notebook here](http://nbviewer.jupyter.org/github/alimanfoo/agam-vgsc-report/blob/df3b3ac22d4efaa2dc2a3e339c8ee693b56f0765/notebooks/explore_haplotype_structure.ipynb) with some new analyses, some interesting results I think, would be cool to talk over tomorrow if possible.

**Comment by alimanfoo** [comment]
Hi @cclarkson, I've pushed some tidying up of the notebook with demos of the various t_hat analyses, [new version is here](http://nbviewer.jupyter.org/github/alimanfoo/agam-vgsc-report/blob/9c79345cf2118bff18a58efce314d60e3b8b719d/notebooks/t_hat_demo.ipynb). If this looks ok to you I'll merge then you can try it out.

**Comment by alimanfoo** [comment]
@hardingnj I think I've finally got a reasonable plotting function that can visualise large trees, what do you think:

image

**Comment by hardingnj** [comment]
A work of art! Really nice work

**Comment by cclarkson** [comment]
Hi @alimanfoo 

Demo notebook looks good :1st_place_medal: 

Have some questions about how we will now define the haplogroups for the paper though - will we continue to use those generated by cutting the distance dendrograms or are we moving to time?

You about for a quick chat?

**Pull request merged**
