### PR TITLE
Supplementary tables & assay design

### LINKED ISSUE #130: Build Supp Tables

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has work on supplementary tables and assay design. Resolves #130.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Apologies this is a bit of a behemoth. Now ready for review. Here's a summary of main changes...

* To get a consistent view on which haplotype group a haplotype belongs to, I've added some code to the [artwork_networks](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/notebooks/artwork_networks.ipynb) notebook to write out a file with group membership. 
* I've then modified the [artwork_hapfreq_map notebook](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/notebooks/artwork_hapfreq_map.ipynb) to use the network groups. This now properly accounts for haplotypes which carry a kdr allele but don't fall into one of the major haplotype groups, by adding a "other kdr" colour (black) to the pies and legend.
* I've then added a [supp_tables notebook](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/notebooks/supp_tables.ipynb) which generates all the supplementary data tables:
    * [supp_table_variants_missense.csv](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/data/supp_table_variants_missense.csv) - all non-synonymous variants, suggest this becomes Supplementary Table 1.
    * [supp_table_variants_tracking.csv](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/data/supp_table_variants_tracking.csv) - variants for tracking haplotype groups, suggest this becomes Supplementary Table 2.
    * [supp_table_variants_all.csv](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/data/supp_table_variants_all.csv) - variants to take into account when doing primer design, suggest this is Supplementary Table 3.
    * [supp_table_haplotype_panel.csv](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/data/supp_table_haplotype_panel.csv) - some meta-information about the haplotypes, including which group we put them in, suggest Supplementary Table 4.
    * There is also [supp_table_haplotypes_tracking.csv](https://github.com/alimanfoo/agam-vgsc-report/blob/9fb16f09316d964a74b6dfb2bb01c35e9455495f/data/supp_table_haplotypes_tracking.csv) which has the actual haplotypes for the tracking variants. Not sure if this is needed.
* Finally, there are some edits to [main.tex](https://github.com/malariagen/agam-vgsc-report/pull/164/files#diff-a45f2757f94fd2337ebf7ddd018c11a2), to consistify language, and also to tighten up the discussion on assay design.

Happy to discuss any aspect of course.

**Comment by cclarkson** [comment]
This all looks great, the tbl_variants_missense with all the isoforms is a particularly a great idea.

Just on thing caught my eye, and that was within the figure legend (line 398) _wt_ is italicised where as later in the text (line 443) it isn't. Was that intentional?

**Comment by alimanfoo** [comment]
Thanks, no not intentional, was just being lazy, we should consistify. I
thought italics looked a bit better and matched italicisation of "kdr", but
happy to do either way. There's a couple of figures IIRC that would also
need updating if we italicize everywhere.

**Comment by alimanfoo** [comment]
Took the liberty of italicizing "wt" throughout text and figures.

**Pull request merged**
