### PR TITLE
mvncall - generated haplotype calls for VGSC multiallelics and 1570

### PR DESCRIPTION
**Pull request by cclarkson**
@alimanfoo 

Just want to check that removing the colony parents from the haps is correct (cut -d' ' -f1-1535 >), otherwise I think this is good to go.

Cheers

### CODE REVIEW

**Comment by alimanfoo** [comment]
Thanks Chris, looks like it's worked OK. 

Can I suggest some file name changes and housekeeping:
* The old "data_phase_multiallelics_phase1.ipynb" notebook is redundant now. Suggest remove it. Also suggest removing the old output data files as these are also now redundant.
* Rename "data_phasing_EXTRA_phase1.ipynb" to all lower case, it feels like you are SHOUTING AT ME :-)
* Rename all the output files from "missense_multiallelics_and_1570.mvncall...." to "phasing_extra_phase1.mvncall..." for consistency with the notebook name. Also rename "vgsc_coding_multiallelics_plus_1570.list" to "phasing_extra_phase1.list" so we know all these files are related.
* Remove the t_hat_demo.ipynb notebook from this PR.

**Comment by alimanfoo** [comment]
Btw to weave in the extras into the biallelic scaffold to build a haplotype array with both, something like this should work (untested):

```
haps_phased_scaffold = ... # load these from disk (callset_phased)
haps_phased_extra = ... # load these from disk (mvncall)
pos_phased_scaffold = ...
pos_phased_extra = ...
haps_combined = np.concatenate([haps_phased_scaffold, haps_phased_extra], axis=0)
pos_combined = np.concatenate([pos_phased_scaffold, pos_phased_extra], axis=0)
idx_sorted = np.argsort(pos_combined)
haps_combined = allel.HaplotypeArray(haps_combined[idx_sorted])
pos_combined = allel.SortedIndex(pos_combined[idx_sorted])
```

**Comment by cclarkson** [comment]
@alimanfoo 

I've cleaned up the files and added an add_multiallelics_to_haplotypes_demo.ipynb which gives a couple of methods for weaving the newly phased loci into the genotype array.

Cheers,

Chris

**Comment by alimanfoo** [comment]
Hi Chris, looks good, couple of nits...

There are two files here with the list of extra SNPs to phase, one at  "data/data_phasing_phase1.list", the other called "data/phasing_extra_phase1.list". Could you remove the first of these. Also could you update the notebook that runs mvncall to point to the second of these.

This is probably my mistake, but now the PR is showing the t_hat_demo notebook as a deletion relative to master, so I think if we merge this it will remove the t_hat_demo notebook. Could you try rebasing on master, so that the t_hat_demo notebook no longer shows up in this PR as any different from master?

Thanks.

**Comment by cclarkson** [comment]
Hi @alimanfoo 

This should be ready to PR now.

**Comment by alimanfoo** [comment]
Thanks Chris.

**Pull request merged**
