### PR TITLE
AJM address Eric comments

### PR DESCRIPTION
**Pull request by alimanfoo**

### CODE REVIEW

**Comment by cclarkson** [comment]
Hi @alimanfoo ,

These all look great except for one change that I fear reviewers may pick up on - 

"or whether they provide some other benefit such as compensating for a mildly deleterious effect of \texttt{L995F} on normal nervous system function."

I'm not sure that there is evidence for it being 'mildy' deleterious, it leaves un-exposed lab populations pretty quickly. Might be a can of worms to get into how deleterious.

C

**Comment by alimanfoo** [comment]
Sure, should I just remove 'mildly'?

**Comment by cclarkson** [comment]
Aye, just remove 'mildy'.

**Comment by alimanfoo** [comment]
Awesome, thanks. Merging...

**Comment by alimanfoo** [comment]
Ah, beat me to it :-)

**Pull request merged**
