### PR TITLE
Non-synonymous SNPs LD analysis

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR adds columns of LD with the two kdr mutations, including both biallelics and multiallelics.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @cclarkson, could you review this please? The PDF with updated Table 1 including LD columns is here: https://github.com/alimanfoo/agam-vgsc-report/blob/581996d9d0b7eea35fe2eecafd4647b5b6dbc568/build/main.pdf

**Comment by alimanfoo** [comment]
Sorry @cclarkson don't review yet, build is broken, need to fix...

**Comment by alimanfoo** [comment]
OK, @cclarkson please review. I've changed this around so that D' values get calculated in the data_variants_phase1 notebook, so they are easy to pull in when building table 1.

PDF is here: https://github.com/alimanfoo/agam-vgsc-report/blob/3fd1a53e216e5f1ed303348971d15535541b7682/build/main.pdf

**Comment by cclarkson** [comment]
Cool, D' there makes sense to me. All looking good.

**Comment by alimanfoo** [comment]
Thanks Chris, merged.

**Pull request merged**
