### PR TITLE
Figure 1 dendro map sm

### PR DESCRIPTION
**Pull request by cclarkson**

### CODE REVIEW

**Comment by alimanfoo** [comment]
Looking good, happy to merge as-is after #39 and #40.

Thinking it might be good to label each pie with country and species, e.g., "GW", "BF gambiae", "BF coluzzii", etc. But we can deal with that as a separate issue/discussion after merging this PR.

**Comment by cclarkson** [comment]
Hi @alimanfoo 

I was just thinking about how to label the pies when I was looking at it the other day, it definitely needs something!

**Comment by alimanfoo** [comment]
Hi Chris, looks like there is a conflict in the clust_dict.pickle file after merging in the other PRs. Could you rebase this PR on upstream/master? clust_dict.pickle should be in upstream/master now, so you could resolve any conflicts via --theirs.

**Comment by cclarkson** [comment]
HI @alimanfoo,
After much faffing, I think I've sorted it!

**Comment by alimanfoo** [comment]
Hi Chris, can we have a quick skype? Not sure this has been rebased fully, lots of files showing up as changed which shouldn't be.

**Comment by cclarkson** [comment]
@alimanfoo 

sure, give me two minutes

**Pull request closed without merging**
