### PR TITLE
Table of missense subsitutions in VGSC

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has initial work on a table of missense (i.e., non-synonymous) substitutions in the VGSC gene.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hey @cclarkson, what do you think of this: https://github.com/alimanfoo/agam-vgsc-report/blob/436e8f9a1ee29e4883af0f2df8a48388a6d68a9c/manuscript/main.pdf

It's not complete, still need to add codon numbering from house fly and also the LD data.

**Comment by cclarkson** [comment]
Oooh, that table looks lovely, I also particularly like the place-holder text! I can did out my housefly-gambiae numbering work so we can fill in that column.

Can we do the LD with scikit allel?

**Comment by alimanfoo** [comment]
>
> Oooh, that table looks lovely
>
Glad you like it, only took me all day :-) Very very slowly getting to
grips with LaTeX...

> I also particularly like the place-holder text! I can did out my
> housefly-gambiae numbering work so we can fill in that column.
>
 That would be awesome.

> Can we do the LD with scikit allel?
>
Sadly no, I haven't implemented D prime, been on my TODO list for ages, now
I have a reason. Also a slight complication that the two multiallelics
won't have been phased, but I think it shouldn't be too hard to phase these
onto the biallelic scaffold with mvncall. I can look into both of these
next week (I'm on leave tomorrow).

-- 
Alistair Miles
Head of Epidemiological Informatics
Centre for Genomics and Global Health <http://cggh.org>
The Wellcome Trust Centre for Human Genetics
Roosevelt Drive
Oxford
OX3 7BN
United Kingdom
Email: alimanfoo@googlemail.com
Web: http://purl.org/net/aliman
Twitter: https://twitter.com/alimanfoo
Tel: +44 (0)1865 287721

**Comment by alimanfoo** [comment]
I'm going to merge this PR into master as it also has some improvements to the install script. We can work on the missing bits of the table in separate PRs.

**Comment by cclarkson** [comment]
Cool, I will branch from the master tomorrow then.

**Pull request merged**
