### PR TITLE
Hapclust utils

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has utility functions for hierarchical clustering and haplotype networks.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hey @cclarkson, check this out: [demo of new haplotype clustering function](https://github.com/alimanfoo/agam-vgsc-report/blob/5c4dfcb1a5d5c72ac22d18518de36c392d85847e/notebooks/hapclust_demo.ipynb).

**Comment by cclarkson** [comment]
Hi @alimanfoo ,

That's awesome. looks great!

**Comment by alimanfoo** [comment]
Working on outputs to other formats now...

**Comment by alimanfoo** [comment]
Hi Chris, I've added a new function "graph_haplotype_network" which should get us most of the way there for making some decent-looking networks. I've added some examples to the end of the [hapclust_demo notebook](https://github.com/alimanfoo/agam-vgsc-report/blob/e323089e1a0002cd83ca05349f9cb6dc26fc6725/notebooks/hapclust_demo.ipynb).

If you think this looks OK then I suggest we merge this PR and take it from there. I haven't figured out how to label the edges yet but we can add that in a later PR.

**Comment by alimanfoo** [comment]
Oh just so I don't forget to mention it, the new network function requires a couple of new packages to be installed. So after merging this and rebasing you'll need to rerun the conda install, which can be done by removing the file 'dependencies/miniconda.installed' then running './install.sh'.

**Comment by alimanfoo** [comment]
I've [updated the demo](https://github.com/alimanfoo/agam-vgsc-report/blob/eb58b1ee836f0803539abe0b87341bbf955eae1d/notebooks/hapclust_demo.ipynb) after playing around a bit with options to control how the edge lengths get adjusted, added in networks for the L995F haplogroups (F1 is the most challenging).

**Comment by alimanfoo** [comment]
OK, merged, bring on the networks!

**Pull request merged**
