### PR TITLE
Redo networks again

### PR DESCRIPTION
**Pull request by cclarkson**
Made mjn network figures.

### CODE REVIEW

**Comment by cclarkson** [comment]
Rebuilt main figure. If this looks okay I will polish (move some edges/labels/nodes around).

**Comment by alimanfoo** [comment]
Thanks Chris. I should look at [complete_networks.svg](https://github.com/cclarkson/agam-vgsc-report/blob/31fc00ea2e97fbcc299d3563495aef76bda15781/artwork/complete_networks.svg) right? Looks good to me.

**Comment by alimanfoo** [comment]
Good to merge?

**Comment by cclarkson** [comment]
Let me give it a quick polish and then we can merge it

**Comment by cclarkson** [comment]
Hi @alimanfoo,

Good to merge.

**Pull request merged**
