### PR TITLE
Refactor data

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR splits out the manuscript and data builds into separate makefiles. This enables outputs from data rules to be properly captured, whilst still maintaining a clear separation between the manuscript build (which can be run during CI checks) and the data build (which needs external data and cannot be run via CI).

The rules previously in a single "Snakefile" have been split into two files "manuscript.rules" and "data.rules". Instructions for building the manuscript and the data have been updated in the README.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @cclarkson, yes I've done it again, modified the build setup... could you take a look and let me know if you're OK or have any questions? This should make it easier to keep data and manuscript build rules separate.

**Comment by cclarkson** [comment]
Hi @alimanfoo, makes sense to me. Can I test if it works or do you need to merge it first?

**Comment by alimanfoo** [comment]
Yeah I think you can test it out before merging. E.g., something like this...

```
$ git checkout -b alimanfoo-refactor_data master
$ git pull https://github.com/alimanfoo/agam-vgsc-report.git refactor_data
$ source env.sh
$ snakemake -s manuscript.rules all
```

**Comment by cclarkson** [comment]
Cool, yep, works fine.

**Comment by alimanfoo** [comment]
Awesome, thanks.

**Comment by alimanfoo** [comment]
Btw if you want a nice editor for the snakemake files, PyCharm is good, there is a community edition for free. When you open a .rules file for the first time, tell PyCharm to use the YAML editor, then you get nice syntax highlighting.

**Pull request merged**
