### PR TITLE
Map artwork 20170912

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has some work on the outbreaks map. Addresses #75.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi Chris, I've done some work on this, will need a bit of discussion I'm sure, main change is revisions to the map:

map

Some points for discussion:

* I have added in points representing results of Clarkson (Ghana) and Norris (Mali) studies. For Ghana we (you) already did the analysis to show this is the F1 haplotype. For Mali we could probably presume. I thought worth adding these data points mainly to show why our uncertainty for the source of the F1 outbreak is broad.
* I have put arrows on both ends of the other spreading outbreaks. This is ambiguous as it could mean we infer movement in both directions, or it could mean we aren't sure. I tried putting a question mark but then that could be interpreted as us not being sure if it's spreading at all - we definitely know it's spreading, just not what direction. 

Any thoughts on these or any other points?

**Comment by alimanfoo** [comment]
Oh, and I did stick with splitting Cameroon mainly for the aesthetics, although the notebook generates a base image for Cameroon as a whole also. Again happy to discuss.

**Comment by cclarkson** [comment]
Looks cool, although I am not too sure about the dashed line around the Western populations. Could this be circular?

Ditching the question marks is sensible.

If we split Cameroon here, would we need to split it elsewhere?

Figure need labels for Norris/Clarkson and the three Cameroon sites.

**Comment by alimanfoo** [comment]
Hi Chris, Dominic has asked for an updated ms to look at tomorrow so I'm going to merge this now, but I'll raise a new issue for further work on the map so please feel free to take a crack at it.

**Pull request merged**
